### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by AlexZvonik** [braintree/braintree-android-drop-in#107]
### General information

* SDK/Library version: 3.4.0
* Environment: Production
* Android Version and Device: Nexus 6, Android 7

### Issue description

I see this crash in Crashlytics.
Weird because my app doesn't call anything related to DropInRequest or DropInActivity

> Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{keoride.sydney/com.braintreepayments.api.dropin.DropInActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.braintreepayments.api.dropin.DropInRequest.a()' on a null object reference
>        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
>        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
>        at android.app.ActivityThread.-wrap12(ActivityThread.java)
>        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
>        at android.os.Handler.dispatchMessage(Handler.java:102)
>        at android.os.Looper.loop(Looper.java:154)
>        at android.app.ActivityThread.main(ActivityThread.java:6119)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
>        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
> 
> Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.braintreepayments.api.dropin.DropInRequest.a()' on a null object reference
>        at com.braintreepayments.api.dropin.BaseActivity.getBraintreeFragment(BaseActivity.java:50)
>        at com.braintreepayments.api.dropin.DropInActivity.onCreate(DropInActivity.java:100)
>        at android.app.Activity.performCreate(Activity.java:6679)
>        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
>        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
>        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
>        at android.app.ActivityThread.-wrap12(ActivityThread.java)
>        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
>        at android.os.Handler.dispatchMessage(Handler.java:102)
>        at android.os.Looper.loop(Looper.java:154)
>        at android.app.ActivityThread.main(ActivityThread.java:6119)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
>        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)

**Comment by quinnjn** [comment]
Looking at the stacktrace, DropinRequest is null.

> Weird because my app doesn't call anything related to DropInRequest or DropInActivity

I'm confused on your statement. If your app doesn't call `DropInRequest` or `DropInActivity` is there a 3rd party library / framework that you're using that is calling Drop-in? Can you explain your app's relationship with Drop-in in more depth?

Thanks!

**Comment by AlexZvonik** [comment]
Hey @quinnjn 
We explicitly use only one class  from this library: `com.braintreepayments.cardform.utils.CardType`
Maybe either `com.braintreepayments:encryption:2.1.0` or `com.braintreepayments.api:braintree:2.13.2` uses `DropInRequest`/`DropInActivity` ?

**Comment by orelvia** [comment]
Hi, this pops up for us again after upgrading to 3.6.0.
We are not calling `DropInActivity` anywhere in our code, still we are seeing this crash in our Crashlytics logs.
Any help would be appreciated

**Comment by scannillo** [comment]
Please see crookedneighbor's solution above.

**Comment by AnastasiyaVia** [comment]
Have the same issue - any support will be very helpfull
