### ISSUE TITLE
StackOverflowError in AddCardActivity.onError

### ISSUE THREAD

**Issue by calvarez-ov** [braintree/braintree-android-drop-in#174]
### General information

* SDK/Library version: `com.braintreepayments.api:drop-in:4.5.0`
* Environment: Sandbox
* Android Version and Device: Robolectric

### Issue description

We've created an espresso test, which runs on robolectric, and launches `AddCardActivity`. It checks that the "save card" checkbox label and "add card" button label have the text we expect (we have redefined the values of these string resources and want this test to break in case the sdk ever changes these string ids).

On our CI, this test passes but then later tests fail with a `StackOverflowError`. I'm not sure yet why. I'll update here if I find more info.

In the meantime, here's the recursive loop repeated a couple of times. Hopefully this is sufficient to identify a potential recursive issue in the drop in ui code.

```
	at com.braintreepayments.api.dropin.AddCardActivity.onError(AddCardActivity.java:371)
	at com.braintreepayments.api.BraintreeFragment$11.run(BraintreeFragment.java:756)
	at com.braintreepayments.api.BraintreeFragment.postOrQueueCallback(BraintreeFragment.java:768)
	at com.braintreepayments.api.BraintreeFragment.postCallback(BraintreeFragment.java:748)
	at com.braintreepayments.api.BraintreeFragment.fetchConfiguration(BraintreeFragment.java:793)
	at com.braintreepayments.api.BraintreeFragment.waitForConfiguration(BraintreeFragment.java:835)
	at com.braintreepayments.api.BraintreeFragment.sendAnalyticsEvent(BraintreeFragment.java:590)
	at com.braintreepayments.api.dropin.AddCardActivity.onError(AddCardActivity.java:371)
	at com.braintreepayments.api.BraintreeFragment$11.run(BraintreeFragment.java:756)
	at com.braintreepayments.api.BraintreeFragment.postOrQueueCallback(BraintreeFragment.java:768)
	at com.braintreepayments.api.BraintreeFragment.postCallback(BraintreeFragment.java:748)
	at com.braintreepayments.api.BraintreeFragment.fetchConfiguration(BraintreeFragment.java:793)
	at com.braintreepayments.api.BraintreeFragment.waitForConfiguration(BraintreeFragment.java:835)
	at com.braintreepayments.api.BraintreeFragment.sendAnalyticsEvent(BraintreeFragment.java:590)
	at com.braintreepayments.api.dropin.AddCardActivity.onError(AddCardActivity.java:371)
	at com.braintreepayments.api.BraintreeFragment$11.run(BraintreeFragment.java:756)
	at com.braintreepayments.api.BraintreeFragment.postOrQueueCallback(BraintreeFragment.java:768)
	at com.braintreepayments.api.BraintreeFragment.postCallback(BraintreeFragment.java:748)
	at com.braintreepayments.api.BraintreeFragment.fetchConfiguration(BraintreeFragment.java:793)
	at com.braintreepayments.api.BraintreeFragment.waitForConfiguration(BraintreeFragment.java:835)
```

Here's what our test does:
```kotlin
@RunWith(AndroidJUnit4::class)
class DropInUiCustomizationTest {
    @get:Rule
    var activityRule = ActivityTestRule<AddCardActivity>(AddCardActivity::class.java, false, false)

    /**
     * Verify that our customized strings are used in the drop-in ui
     */
    @Test
    fun testDropInUiCustomization() {
        val token = "eyJ2ZXJzaW9uIjoy ... snip ... GVjb21FVVIifQ=="
        val dropInRequest = DropInRequest()
                .clientToken(token)
                .vaultCard(false)
                .allowVaultCardOverride(true)
                .vaultManager(true)
                .disablePayPal()
        val intent = Intent(ApplicationProvider.getApplicationContext(), AddCardActivity::class.java)
                .putExtra(DropInRequest.EXTRA_CHECKOUT_REQUEST, dropInRequest)
        val activity = activityRule.launchActivity(intent)
        getInstrumentation().runOnMainSync {
            activity.findViewById<ViewGroup>(R.id.bt_edit_card_view).let { editCardView ->

                val checkbox = editCardView.findViewById<CheckBox>(R.id.bt_card_form_save_card_checkbox)
                assertEquals(activity.getString(R.string.bt_save_card_checkbox_name), checkbox.text.toString())

                val button = editCardView.findViewById<ViewGroup>(R.id.bt_animated_button_view).findViewById<Button>(R.id.bt_button)
                assertEquals(activity.getString(R.string.bt_add_card).toLowerCase(Locale.US),
                        button.text.toString().toLowerCase(Locale.US))

            }
        }
    }

}
```

**Comment by sshropshire** [comment]
Hi @calvarez-ov thank you for using the Braintree SDK for Android.

At a first glance, it appears BraintreeFragment is having trouble fetching configuration. Are you able to check if the CI environment has access to the internet?

**Comment by calvarez-ov** [comment]
Hi @sshropshire thanks for the quick reply

Actually I can reproduce this on my PC as well. If I just run the test, it passes. If I put breakpoints in the `onError` or related methods, I hit them and end up with a `StackOverflowError`.

Indeed there must be some configuration error. I'm looking into that right now. But I'm guessing there's an issue with the sdk nentering a recursive loop when this error occurs.

It could also be related to the fact that it's running on Robolectric, which runs everything synchronously on a single thread.

I'll update here when I find more info.

**Comment by sshropshire** [comment]
@calvarez-ov that is a fair assumption. Our HttpClient uses Android Handler and Looper classes for posting HttpResponse callbacks. There could be some differences between the Robolectric implementation and actual Android.

**Comment by calvarez-ov** [comment]
Indeed I have an authorization issue. The token I hardcoded in the test: it was valid when I wrote the test, but I guess not anymore 😄 I thought I would just need a token in a specific format, but I guess I need a token which is still valid.I was hoping to test the `CardActivity` UI without having to go through authentication.  There's no test token by chance is there?

**Comment by calvarez-ov** [comment]
BTW, the whole reason we wanted to customize a couple of strings (and thus add this test to check for regressions in future updates) is because the French texts are confusing:

`bt_add_card`: "Enregistrer une carte"
`bt_save_card_checkbox_name`: "Enregistrer une carte"

Both mean "add a card". So French users were confused to see a checkbox "add a card", and when they leave it unchecked, the button says "add a card". 

So I guess, if these translations could be improved, we could remove our customization, and this test, and pretend we never saw the `StackOverflowError` 😄

**Comment by sshropshire** [comment]
@calvarez-ov that's understandable. Client tokens are valid for 24 hours. I'll close this issue then since the authentication issue is resolved.

In regards to localization, you can open a separate issue with the suggested translations, and we can forward it to our dedicated localization team.

**Comment by calvarez-ov** [comment]
Opened #175
