### ISSUE TITLE
Class not found when unmarshalling: com.braintreepayments.api.dropin.DropInRequest

### ISSUE THREAD

**Issue by Ge0** [braintree/braintree-android-drop-in#191]
### General information

* SDK/Library version: 4.6.0
* Environment: Sandbox
* Android Version and Device: Samsung Galaxy S10 with Android 10.0

### Issue description

I cannot even make work the "hello world" equivalent described on this page: https://developers.braintreepayments.com/start/hello-client/android/v3

I have added the following snippet:

```
        button.setOnClickListener {
            val dropInRequest = DropInRequest()
                    .clientToken("CLIENT_TOKEN_FROM_SERVER")
            startActivityForResult(dropInRequest.getIntent(this), REQUEST_CODE)
        }
```

And I get the following stack trace:

```
2020-08-18 10:32:09.777 5841-15936/? E/Parcel: Class not found when unmarshalling: com.braintreepayments.api.dropin.DropInRequest
    java.lang.ClassNotFoundException: com.braintreepayments.api.dropin.DropInRequest
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at android.os.Parcel.readParcelableCreator(Parcel.java:3031)
        at android.os.Parcel.readParcelable(Parcel.java:2981)
        at android.os.Parcel.readValue(Parcel.java:2883)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3261)
        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
        at android.os.BaseBundle.unparcel(BaseBundle.java:236)
        at android.os.BaseBundle.getString(BaseBundle.java:1160)
        at android.content.Intent.getStringExtra(Intent.java:8548)
        at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:790)
        at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:694)
        at com.android.server.wm.ActivityStarter.startActivityMayWait(ActivityStarter.java:1925)
        at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:625)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1707)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1603)
        at com.android.server.wm.ActivityTaskManagerService.startActivity(ActivityTaskManagerService.java:1557)
        at android.app.IActivityTaskManager$Stub.onTransact(IActivityTaskManager.java:1690)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
     Caused by: java.lang.ClassNotFoundException: com.braintreepayments.api.dropin.DropInRequest
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:454) 
        at android.os.Parcel.readParcelableCreator(Parcel.java:3031) 
        at android.os.Parcel.readParcelable(Parcel.java:2981) 
        at android.os.Parcel.readValue(Parcel.java:2883) 
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3261) 
        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292) 
        at android.os.BaseBundle.unparcel(BaseBundle.java:236) 
        at android.os.BaseBundle.getString(BaseBundle.java:1160) 
        at android.content.Intent.getStringExtra(Intent.java:8548) 
        at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:790) 
        at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:694) 
        at com.android.server.wm.ActivityStarter.startActivityMayWait(ActivityStarter.java:1925) 
        at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:625) 
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1707) 
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1603) 
        at com.android.server.wm.ActivityTaskManagerService.startActivity(ActivityTaskManagerService.java:1557) 
        at android.app.IActivityTaskManager$Stub.onTransact(IActivityTaskManager.java:1690) 
        at android.os.Binder.execTransactInternal(Binder.java:1021) 
        at android.os.Binder.execTransact(Binder.java:994) 
```

Someone got the same error detailed here: https://stackoverflow.com/questions/54221312/braintree-integration-error-class-not-found-com-braintreepayments-api-dropin but no answer.

Please note that I have even tried with a token generated from my server, but this should not be taken into account.

Moreover I cannot understand the situation which has been discussed in #57.

So if you guys have an idea of what's going on, any help would be very appreciated.

Thanks!

**Comment by sshropshire** [comment]
Hi @Ge0 thanks for using the Braintree SDK for Android. The issue appears to be with classloading and `Parcelable`. I'm unable to reproduce on my machine; however, I'm curious are you able to reproduce this error in an emulator on your workstation?

**Comment by Ge0** [comment]
Hi @sshropshire and thanks for the quick answer.

I cannot reproduce the error in an emulator (Pixel 2 API level 29). I don't get the stack trace but nothing is happening anyway.

I am wondering if this error has something do to with my packages' versions…

```gradle
dependencies {
    def nav_version = "2.0.0" // Here we keep 2.0.0 for compat purpose. Do not upgrade to 2.1.0 yet.
    def lifecycle_version = "2.1.0"
    def work_version = "2.2.0"
    def bugfender_version = '3.0.5'
    def stripe_version = '14.5.0'
    def room_version = "2.2.5"
    def braintree_version = "3.13.0"
    def braintree_dropin_version = "4.6.0"

    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.preference:preference:1.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    implementation 'com.google.android.material:material:1.1.0-beta01'
    implementation "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"

    implementation "androidx.constraintlayout:constraintlayout:1.1.3"
    implementation "androidx.navigation:navigation-fragment:$nav_version"
    implementation "androidx.navigation:navigation-ui:$nav_version"
    implementation "androidx.lifecycle:lifecycle-extensions:$lifecycle_version"
    implementation "androidx.navigation:navigation-fragment-ktx:$nav_version"
    implementation "androidx.navigation:navigation-ui-ktx:$nav_version"
    implementation 'com.google.code.gson:gson:2.8.6'

    implementation 'com.lamudi.phonefield:phone-field:0.1.3'


    implementation 'com.android.volley:volley:1.1.1'

    implementation "androidx.work:work-runtime-ktx:$work_version"
    
    implementation 'androidx.core:core:1.0.1'

    implementation "com.stripe:stripe-android:$stripe_version"

    testImplementation 'junit:junit:4.12'
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.3.1'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.3.1'
    testRuntimeOnly "org.junit.vintage:junit-vintage-engine:5.6.2"

    androidTestImplementation 'androidx.test:runner:1.2.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'

    implementation 'com.facebook.android:facebook-android-sdk:5.15.0'

    implementation 'com.google.firebase:firebase-analytics:17.2.2'

    // Add the Firebase Crashlytics dependency.
    implementation 'com.google.firebase:firebase-crashlytics:17.1.1'
    //implementation 'com.google.firebase:firebase-crashlytics-ndk:17.1.1'

    implementation 'com.google.firebase:firebase-messaging:20.2.3'

    //implementation 'org.slf4j:slf4j-api:1.7.27'
    implementation 'com.github.tony19:logback-android:2.0.0'
    /*
    implementation ('com.papertrailapp:logback-syslog4j:1.0.0') {
        exclude group: 'ch.qos.logback'
    }
     */

    implementation "com.bugfender.sdk:android:$bugfender_version"

    implementation "androidx.room:room-runtime:$room_version"
    kapt "androidx.room:room-compiler:$room_version"
    testImplementation "androidx.room:room-testing:$room_version"

    implementation "com.braintreepayments.api:drop-in:$braintree_dropin_version"
    implementation "com.braintreepayments.api:braintree:$braintree_version"

    implementation project(":dicle")
}
```

**Comment by Ge0** [comment]
Instead I get this log info (not error) :

```
2020-08-18 19:13:27.280 2023-4340/? I/ActivityTaskManager: START u0 {cmp=com.flexomatic.dev/com.braintreepayments.api.dropin.DropInActivity (has extras)} from uid 10136
```

But the activity ain't showing.

**Comment by sshropshire** [comment]
Hey @Ge0 as an attempt to resolve the issue, could you remove the line `implementation "com.braintreepayments.api:braintree:$braintree_version"` from your gradle file?

Drop In bundles the core sdk as a dependency and it's worth a shot to test if that clears up any ambiguity with the Parcelable class loader.

**Comment by Ge0** [comment]
Hey @sshropshire,

In the meantime I’ve got in touch with Braintree's support and they already pointed this out and it did not change anything.

At this time I am kept quite busy anyway so I’ll pause this issue and I’ll try a few things out later with different devices and so on.

I’ll keep you posted.

Thanks!

**Comment by prashangc** [comment]
@Ge0 do u have the solution for it now?

**Comment by Ge0** [comment]
@prashangc I’ve removed braintree from my app.

**Comment by sshropshire** [comment]
Hi @prashangc thanks for using the Braintree SDK for Android. We're working on a new [beta](https://github.com/braintree/braintree-android-drop-in/blob/master/CHANGELOG.md#600-beta2) of our DropIn library to address issues like these and improve the developer experience. If you're able to reproduce in the latest `6.0.0-beta2` version let us know, and we'll work on getting a fix out as soon as we can.
