### ISSUE TITLE
Braintree 3ds internal crash with Android 12 support.

### ISSUE THREAD

**Issue by bm185178** [braintree/braintree-android-drop-in#309]
### General information

* SDK/Library version: 5.3.0
* Environment: Sandbox & Production
* Android Version and Device: Android 12 and all devices

### Issue description

Braintree 3ds internal crash with Android 12 support. Something to do with cardinal mobile SDK. Please someone investigate this.

```
11-08 19:57:56.555   724  1100 F libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 1100 (bt_hci_thread), pid 724 (droid.bluetooth)
11-09 10:10:22.640 11666 11707 F libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 11707 (bt_hci_thread), pid 11666 (droid.bluetooth)
11-12 11:27:21.621 20776 20776 E AndroidRuntime: FATAL EXCEPTION: main
11-12 11:27:21.621 20776 20776 E AndroidRuntime: Process: com.kfcaus.ordering.beta, PID: 20776
11-12 11:27:21.621 20776 20776 E AndroidRuntime: java.lang.SecurityException: Need android.permission.BLUETOOTH_CONNECT permission for AttributionSource { uid = 10154, packageName = com.kfcaus.ordering.beta, attributionTag = null, token = android.os.BinderProxy@39db172, next = null }: getAddress
11-12 11:27:21.621 20776 20776 E AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
11-12 11:27:21.621 20776 20776 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:2409)
11-12 11:27:21.621 20776 20776 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2392)
11-12 11:27:21.621 20776 20776 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2334)
11-12 11:27:21.621 20776 20776 E AndroidRuntime: 	at android.bluetooth.IBluetoothManager$Stub$Proxy.getAddress(IBluetoothManager.java:773)
11-12 11:27:21.621 20776 20776 E AndroidRuntime: 	at android.bluetooth.BluetoothAdapter.getAddress(BluetoothAdapter.java:1279)
11-12 11:27:21.621 20776 20776 E AndroidRuntime: 	at com.cardinalcommerce.shared.cs.f.b.<init>(Unknown Source:23)
11-12 11:27:21.621 20776 20776 E AndroidRuntime: 	at com.cardinalcommerce.shared.cs.f.g.b(Unknown Source:69)
11-12 11:27:21.621 20776 20776 E AndroidRuntime: 	at com.cardinalcommerce.shared.cs.f.g.a(Unknown Source:7)
11-12 11:27:21.621 20776 20776 E AndroidRuntime: 	at com.cardinalcommerce.shared.cs.a.b.a(Unknown Source:2)
11-12 11:27:21.621 20776 20776 E AndroidRuntime: 	at com.cardinalcommerce.cardinalmobilesdk.a.a.a.a(Unknown Source:123)
11-12 11:27:21.621 20776 20776 E AndroidRuntime: 	at com.cardinalcommerce.cardinalmobilesdk.Cardinal.configure(Unknown Source:24)
11-12 11:27:21.621 20776 20776 E AndroidRuntime: 	at com.braintreepayments.api.ThreeDSecure.configureCardinal(ThreeDSecure.java:391)
11-12 11:27:21.621 20776 20776 E AndroidRuntime: 	at com.braintreepayments.api.ThreeDSecure.access$100(ThreeDSecure.java:47)
11-12 11:27:21.621 20776 20776 E AndroidRuntime: 	at com.braintreepayments.api.ThreeDSecure$4.onConfigurationFetched(ThreeDSecure.java:220)
11-12 11:27:21.621 20776 20776 E AndroidRuntime: 	at com.braintreepayments.api.BraintreeFragment$14.run(BraintreeFragment.java:886)
11-12 11:27:21.621 20776 20776 E AndroidRuntime: 	at com.braintreepayments.api.BraintreeFragment.postOrQueueCallback(BraintreeFragment.java:809)
11-12 11:27:21.621 20776 20776 E AndroidRuntime: 	at com.braintreepayments.api.BraintreeFragment.waitForConfiguration(BraintreeFragment.java:878)
11-12 11:27:21.621 20776 20776 E AndroidRuntime: 	at com.braintreepayments.api.ThreeDSecure.performVerification(ThreeDSecure.java:185)
11-12 11:27:21.621 20776 20776 E AndroidRuntime: 	at com.braintreepayments.api.ThreeDSecure.performVerification(ThreeDSecure.java:159)
11-12 11:27:21.621 20776 20776 E AndroidRuntime: 	at com.braintreepayments.api.dropin.AddCardActivity.onPaymentMethodNonceCreated(AddCardActivity.java:308)
11-12 11:27:21.621 20776 20776 E AndroidRuntime: 	at com.braintreepayments.api.BraintreeFragment$4.run(BraintreeFragment.java:696)
11-12 11:27:21.621 20776 20776 E AndroidRuntime: 	at com.braintreepayments.api.BraintreeFragment.postOrQueueCallback(BraintreeFragment.java:809)
11-12 11:27:21.621 20776 20776 E AndroidRuntime: 	at com.braintreepayments.api.BraintreeFragment.postCallback(BraintreeFragment.java:688)
11-12 11:27:21.621 20776 20776 E AndroidRuntime: 	at com.braintreepayments.api.Card$1.success(Card.java:35)
11-12 11:27:21.621 20776 20776 E AndroidRuntime: 	at com.braintreepayments.api.TokenizationClient$2.success(TokenizationClient.java:73)
11-12 11:27:21.621 20776 20776 E AndroidRuntime: 	at com.braintreepayments.api.internal.HttpClient$3.run(HttpClient.java:288)
11-12 11:27:21.621 20776 20776 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
11-12 11:27:21.621 20776 20776 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
11-12 11:27:21.621 20776 20776 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
11-12 11:27:21.621 20776 20776 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
11-12 11:27:21.621 20776 20776 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7842)
11-12 11:27:21.621 20776 20776 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-12 11:27:21.621 20776 20776 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
11-12 11:27:21.621 20776 20776 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
11-12 11:27:21.621 20776 20776 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
11-12 11:27:21.621 20776 20776 E AndroidRuntime: 	at com.android.server.BluetoothManagerService.checkPermissionForDataDelivery(BluetoothManagerService.java:2918)
11-12 11:27:21.621 20776 20776 E AndroidRuntime: 	at com.android.server.BluetoothManagerService.checkConnectPermissionForDataDelivery(BluetoothManagerService.java:2936)
11-12 11:27:21.621 20776 20776 E AndroidRuntime: 	at com.android.server.BluetoothManagerService.getAddress(BluetoothManagerService.java:1703)
11-12 11:27:21.621 20776 20776 E AndroidRuntime: 	at android.bluetooth.IBluetoothManager$Stub.onTransact(IBluetoothManager.java:365)
11-12 11:27:21.621 20776 20776 E AndroidRuntime: 	at android.os.Binder.execTransactInternal(Binder.java:1179)
```

**Comment by sshropshire** [comment]
@bm185178 thank you for using the Braintree SDK for Android. Please refer to [#474](https://github.com/braintree/braintree_android/issues/474) in our core repo.
