### ISSUE TITLE
App is crash when we add ThreeDSecureRequest in DropInRequest. I have use this com.braintreepayments.api:drop-in:6.0.2

### ISSUE THREAD

**Issue by ranatalaldev** [braintree/braintree-android-drop-in#342]
2022-05-11 15:17:09.404 27833-27833/com.example.braintreeexample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.braintreeexample, PID: 27833
    java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/content/ContextCompat;
        at com.cardinalcommerce.shared.cs.f.h.<init>(Unknown Source:27)
        at com.cardinalcommerce.shared.cs.f.c.a(Unknown Source:2)
        at com.cardinalcommerce.shared.cs.f.c.<init>(Unknown Source:3)
        at com.cardinalcommerce.shared.cs.f.g.a(Unknown Source:2)
        at com.cardinalcommerce.shared.cs.a.b.a(Unknown Source:2)
        at com.cardinalcommerce.cardinalmobilesdk.a.a.a.a(Unknown Source:132)
        at com.cardinalcommerce.cardinalmobilesdk.Cardinal.configure(Unknown Source:24)
        at com.braintreepayments.api.CardinalClient.configurationCardinal(CardinalClient.java:62)
        at com.braintreepayments.api.CardinalClient.initialize(CardinalClient.java:21)
        at com.braintreepayments.api.ThreeDSecureClient$1.onResult(ThreeDSecureClient.java:104)
        at com.braintreepayments.api.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:41)
        at com.braintreepayments.api.BraintreeClient.getConfiguration(BraintreeClient.java:130)
        at com.braintreepayments.api.ThreeDSecureClient.performVerification(ThreeDSecureClient.java:68)
        at com.braintreepayments.api.DropInClient.performThreeDSecureVerification(DropInClient.java:107)
        at com.braintreepayments.api.DropInActivity.lambda$onPaymentMethodNonceCreated$17$com-braintreepayments-api-DropInActivity(DropInActivity.java:494)
        at com.braintreepayments.api.DropInActivity$$ExternalSyntheticLambda7.onResult(Unknown Source:4)
        at com.braintreepayments.api.DropInClient.lambda$shouldRequestThreeDSecureVerification$3$com-braintreepayments-api-DropInClient(DropInClient.java:141)
        at com.braintreepayments.api.DropInClient$$ExternalSyntheticLambda11.onResult(Unknown Source:4)
        at com.braintreepayments.api.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:41)
        at com.braintreepayments.api.BraintreeClient.getConfiguration(BraintreeClient.java:130)
        at com.braintreepayments.api.DropInClient.shouldRequestThreeDSecureVerification(DropInClient.java:133)
        at com.braintreepayments.api.DropInActivity.onPaymentMethodNonceCreated(DropInActivity.java:492)
        at com.braintreepayments.api.DropInActivity.lambda$onCardDetailsSubmit$15$com-braintreepayments-api-DropInActivity(DropInActivity.java:487)
        at com.braintreepayments.api.DropInActivity$$ExternalSyntheticLambda11.onResult(Unknown Source:2)
        at com.braintreepayments.api.CardClient.handleTokenizeResponse(CardClient.java:91)
        at com.braintreepayments.api.CardClient.access$100(CardClient.java:14)
        at com.braintreepayments.api.CardClient$1$1.onResult(CardClient.java:68)
        at com.braintreepayments.api.ApiClient$1.onResult(ApiClient.java:38)
        at com.braintreepayments.api.HttpClient$2.run(HttpClient.java:123)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.content.ContextCompat" on path: DexPathList[[dex file "/data/data/com.example.braintreeexample/code_cache/.overlay/base.apk/classes3.dex", zip file "/data/app/~~HPIymU3ZtyLav4M8YNGDiA==/com.example.braintreeexample-KT3fb9pdnxbvbUZbse2vcw==/base.apk"],nativeLibraryDirectories=[/data/app/~~HPIymU3ZtyLav4M8YNGDiA==/com.example.braintreeexample-KT3fb9pdnxbvbUZbse2vcw==/lib/x86, /system/lib, /system_ext/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.cardinalcommerce.shared.cs.f.h.<init>(Unknown Source:27) 
        at com.cardinalcommerce.shared.cs.f.c.a(Unknown Source:2) 
        at com.cardinalcommerce.shared.cs.f.c.<init>(Unknown Source:3) 
        at com.cardinalcommerce.shared.cs.f.g.a(Unknown Source:2) 
        at com.cardinalcommerce.shared.cs.a.b.a(Unknown Source:2) 
        at com.cardinalcommerce.cardinalmobilesdk.a.a.a.a(Unknown Source:132) 
        at com.cardinalcommerce.cardinalmobilesdk.Cardinal.configure(Unknown Source:24) 
        at com.braintreepayments.api.CardinalClient.configurationCardinal(CardinalClient.java:62) 
        at com.braintreepayments.api.CardinalClient.initialize(CardinalClient.java:21) 
        at com.braintreepayments.api.ThreeDSecureClient$1.onResult(ThreeDSecureClient.java:104) 
        at com.braintreepayments.api.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:41) 
        at com.braintreepayments.api.BraintreeClient.getConfiguration(BraintreeClient.java:130) 
        at com.braintreepayments.api.ThreeDSecureClient.performVerification(ThreeDSecureClient.java:68) 
        at com.braintreepayments.api.DropInClient.performThreeDSecureVerification(DropInClient.java:107) 
        at com.braintreepayments.api.DropInActivity.lambda$onPaymentMethodNonceCreated$17$com-braintreepayments-api-DropInActivity(DropInActivity.java:494) 
        at com.braintreepayments.api.DropInActivity$$ExternalSyntheticLambda7.onResult(Unknown Source:4) 
        at com.braintreepayments.api.DropInClient.lambda$shouldRequestThreeDSecureVerification$3$com-braintreepayments-api-DropInClient(DropInClient.java:141) 
        at com.braintreepayments.api.DropInClient$$ExternalSyntheticLambda11.onResult(Unknown Source:4) 
        at com.braintreepayments.api.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:41) 
        at com.braintreepayments.api.BraintreeClient.getConfiguration(BraintreeClient.java:130) 
        at com.braintreepayments.api.DropInClient.shouldRequestThreeDSecureVerification(DropInClient.java:133) 
        at com.braintreepayments.api.DropInActivity.onPaymentMethodNonceCreated(DropInActivity.java:492) 
        at com.braintreepayments.api.DropInActivity.lambda$onCardDetailsSubmit$15$com-braintreepayments-api-DropInActivity(DropInActivity.java:487) 
        at com.braintreepayments.api.DropInActivity$$ExternalSyntheticLambda11.onResult(Unknown Source:2) 
        at com.braintreepayments.api.CardClient.handleTokenizeResponse(CardClient.java:91) 
        at com.braintreepayments.api.CardClient.access$100(CardClient.java:14) 
        at com.braintreepayments.api.CardClient$1$1.onResult(CardClient.java:68) 
        at com.braintreepayments.api.ApiClient$1.onResult(ApiClient.java:38) 
        at com.braintreepayments.api.HttpClient$2.run(HttpClient.java:123) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by sarahkoop** [comment]
Hi @ranatalaldev - This error looks like it's coming from an Android support library. Do you have `enableJetifier=true` set in your `gradle.properties` file?

**Comment by ranatalaldev** [comment]
Hi @sarahkoop I m try this one but same issue face

**Comment by sarahkoop** [comment]
Hi @ranatalaldev, can you confirm if you still see the error after the following steps:

1) Add the following to your `gradle.properties`:
```
android.useAndroidX=true
android.enableJetifier=true
```

2) In Android Studio, invalidate caches and restart the IDE.
