### ISSUE TITLE
IllegalStateException instantiating DropInClient in started activity

### ISSUE THREAD

**Issue by paolomanca** [braintree/braintree-android-drop-in#343]
### General information

* SDK/Library version: 6.1.0
* Environment: sandbox
* Android Version and Device: any
### Issue description

I'm trying to upgrade to version 6.1.0 where the constructor DropInClient(Context, String, DropInRequest) is deprecated. However, new constructors throw

```
java.lang.IllegalStateException: LifecycleOwner [omissis].MainActivity@4e33d58 is attempting to register while current state is RESUMED. LifecycleOwners must call register before they are STARTED.
        at androidx.activity.result.ActivityResultRegistry.register(ActivityResultRegistry.java:123)
        at com.braintreepayments.api.DropInLifecycleObserver.onCreate(DropInLifecycleObserver.java:30)
        at androidx.lifecycle.FullLifecycleObserverAdapter.onStateChanged(FullLifecycleObserverAdapter.java:36)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
        at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:196)
        at com.braintreepayments.api.DropInClient.addObserver(DropInClient.java:175)
        at com.braintreepayments.api.DropInClient.<init>(DropInClient.java:169)
        at com.braintreepayments.api.DropInClient.<init>(DropInClient.java:126)
       [...]
```
when the referenced FragmentActivity is already started, which wasn't the case with the deprecated constructor.
I can't instantiate the client before in the activity, since I don't have all the details from the user to construct the DropInRequest, unless I launch a dedicated one (which I'd prefer not to).
Is this the intended behaviour?

**Comment by paolomanca** [comment]
Hi @sshropshire, thank you for your answer.

What's preventing me from instantiating in `onCreate` it's not the client token, for which I'm using the `ClientTokenProvider` you mentioned, but the `ThreeDSecureRequest` to be set in the `DropInRequest`.
As far as I know, it can't be deferred and, since it requires at least the `amount`, I can't really instantiate it before in the activity without launching a new one on checkout.

**Comment by mtrakal** [comment]
Hi, is there any progress in move `DropInRequest` to `start()` or `launchDropIn()` method?

**Comment by sshropshire** [comment]
Hi @mtrakal we do have a pull request #358 up to make this change. We're doing our due diligence to get it merged in. We don't have an expected timeline on completion, but I'd expect it to be available in the next release.

Also feel free to review the PR!
