### ISSUE TITLE
[Question] If Jetifier needs to be enabled for latest version of the SDK

### ISSUE THREAD

**Issue by piotrmadry** [braintree/braintree-android-drop-in#349]
### General information

* SDK/Library version: 5.2.2
* Environment: Both Sandbox and Production
* Android Version and Device: Android 10, One Plus 6

### Issue description

For the latest version of the SDK (6.1.0) do we still need Jetifier to be enabled to make SDK work? Currently, it's crashing error

```
022-07-04 11:04:33.640 17952-17952/com.fishbrain.app.debug E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.fishbrain.app.debug, PID: 17952
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/content/ContextCompat;
at com.cardinalcommerce.shared.cs.f.h.<init>(Unknown Source:27)
at com.cardinalcommerce.shared.cs.f.c.a(Unknown Source:2)
at com.cardinalcommerce.shared.cs.f.c.<init>(Unknown Source:3)
at com.cardinalcommerce.shared.cs.f.g.a(Unknown Source:2)
at com.cardinalcommerce.shared.cs.a.b.a(Unknown Source:2)
at com.cardinalcommerce.cardinalmobilesdk.a.a.a.a(Unknown Source:123)
at com.cardinalcommerce.cardinalmobilesdk.Cardinal.configure(Unknown Source:24)
at com.braintreepayments.api.ThreeDSecure.configureCardinal(ThreeDSecure.java:391)
at com.braintreepayments.api.ThreeDSecure.access$100(ThreeDSecure.java:47)
at com.braintreepayments.api.ThreeDSecure$4.onConfigurationFetched(ThreeDSecure.java:220)
at com.braintreepayments.api.BraintreeFragment$14.run(BraintreeFragment.java:886)
at com.braintreepayments.api.BraintreeFragment.postOrQueueCallback(BraintreeFragment.java:809)
at com.braintreepayments.api.BraintreeFragment.waitForConfiguration(BraintreeFragment.java:878)
at com.braintreepayments.api.ThreeDSecure.performVerification(ThreeDSecure.java:185)
at com.braintreepayments.api.ThreeDSecure.performVerification(ThreeDSecure.java:159)
at com.braintreepayments.api.dropin.DropInActivity.onPaymentMethodNonceCreated(DropInActivity.java:220)
at com.braintreepayments.api.BraintreeFragment$4.run(BraintreeFragment.java:696)
at com.braintreepayments.api.BraintreeFragment.flushCallbacks(BraintreeFragment.java:819)
at com.braintreepayments.api.BraintreeFragment.addListener(BraintreeFragment.java:506)
at com.braintreepayments.api.BraintreeFragment.onResume(BraintreeFragment.java:316)
at androidx.fragment.app.Fragment.performResume(Fragment.java:3071)
at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:605)
at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:285)
at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1374)
at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2841)
at androidx.fragment.app.FragmentManager.dispatchResume(FragmentManager.java:2798)
at androidx.fragment.app.FragmentController.dispatchResume(FragmentController.java:284)
at androidx.fragment.app.FragmentActivity.onResumeFragments(FragmentActivity.java:434)
at androidx.fragment.app.FragmentActivity.onPostResume(FragmentActivity.java:423)
at androidx.appcompat.app.AppCompatActivity.onPostResume(AppCompatActivity.java:240)
at android.app.Activity.performResume(Activity.java:7977)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4312)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4354)
at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2109)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7682)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
2022-07-04 11:04:33.640 17952-17952/com.fishbrain.app.debug E/AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.content.ContextCompat" on path: DexPathList[[zip file "/data/app/com.fishbrain.app.debug-weNpXOGJyIbXEILxfjofNA==/base.apk"],nativeLibraryDirectories=[/data/app/com.fishbrain.app.debug-weNpXOGJyIbXEILxfjofNA==/lib/arm64, /data/app/com.fishbrain.app.debug-weNpXOGJyIbXEILxfjofNA==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
```

**Comment by sshropshire** [comment]
Hi @piotrmadry thanks for using the Braintree SDK for Android. Are you using our latest [6.1.0](https://github.com/braintree/braintree-android-drop-in/blob/master/CHANGELOG.md#610) version? I double checked and removed it from our [Demo application](https://github.com/braintree/braintree-android-drop-in/pull/351) and everything appears to work fine.
