### ISSUE TITLE
Regarding onDropInFailure: User Canceled Dropin

### ISSUE THREAD

**Issue by rohitgarg29** [braintree/braintree-android-drop-in#390]
Hi BrainTree Team,

I am working on resolving the CardinalComm SDK changes, I have updated the android-drop-in to latest version 6.6.0. I am facing one problem:

 I am getting the following error on LaunchDropIn.  **onDropInFailure: brain tree error com.braintreepayments.api.UserCanceledException: User canceled DropIn.** it is not even showing the select payment method dialog, "Google Pay, PayPal, Debit or Credit card one". Also I am not even canceling the or doing anything. 

**IsExplicitCancelation = false** 

Thanks in advance. As I am on time crunch, Please Help!

**Comment by scannillo** [comment]
👋 Hi @rohitgarg29 - thanks for using the Braintree Android Drop-In SDK.

This issue thread is for if think you've found an issue with our SDK. 

Your issue sounds instead like you need help troubleshooting your integration, so we recommend you reach out to Braintree Support at https://help.braintreepayments.com. They will need steps to replicate your issue. Also, please refer to our integration documentation [here](https://developer.paypal.com/braintree/docs/guides/drop-in/setup-and-integration), to make sure you have everything set up correctly.

If you still think there is a bug with our SDK, please let us know here!

**Comment by rohitgarg29** [comment]
Hi @scannillo Thanks for replying.

I am not sure, Implementation is pretty straight forward. I am doing all whatever is required,  What are the reasons for "IsExplicitCancelation = false". I am posting the stacktrace as well here. 

```
com.braintreepayments.api.UserCanceledException: User canceled DropIn.
2023-01-24 00:13:53.417 16616-16616/com.arriva.debug W/System.err:     at com.braintreepayments.api.DropInActivityResultContract.parseResult(DropInActivityResultContract.java:39)
2023-01-24 00:13:53.417 16616-16616/com.arriva.debug W/System.err:     at com.braintreepayments.api.DropInActivityResultContract.parseResult(DropInActivityResultContract.java:18)
2023-01-24 00:13:53.417 16616-16616/com.arriva.debug W/System.err:     at androidx.activity.result.ActivityResultRegistry.doDispatch(ActivityResultRegistry.java:392)
2023-01-24 00:13:53.417 16616-16616/com.arriva.debug W/System.err:     at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.java:351)
2023-01-24 00:13:53.417 16616-16616/com.arriva.debug W/System.err:     at androidx.activity.ComponentActivity.onActivityResult(ComponentActivity.java:638)
2023-01-24 00:13:53.417 16616-16616/com.arriva.debug W/System.err:     at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:140)
2023-01-24 00:13:53.417 16616-16616/com.arriva.debug W/System.err:     at android.app.Activity.dispatchActivityResult(Activity.java:8659)
2023-01-24 00:13:53.417 16616-16616/com.arriva.debug W/System.err:     at android.app.ActivityThread.deliverResults(ActivityThread.java:5857)
2023-01-24 00:13:53.417 16616-16616/com.arriva.debug W/System.err:     at android.app.ActivityThread.handleSendResult(ActivityThread.java:5903)
2023-01-24 00:13:53.417 16616-16616/com.arriva.debug W/System.err:     at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:54)
2023-01-24 00:13:53.417 16616-16616/com.arriva.debug W/System.err:     at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
2023-01-24 00:13:53.417 16616-16616/com.arriva.debug W/System.err:     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
2023-01-24 00:13:53.417 16616-16616/com.arriva.debug W/System.err:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
2023-01-24 00:13:53.417 16616-16616/com.arriva.debug W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
2023-01-24 00:13:53.417 16616-16616/com.arriva.debug W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
2023-01-24 00:13:53.417 16616-16616/com.arriva.debug W/System.err:     at android.os.Looper.loopOnce(Looper.java:226)
2023-01-24 00:13:53.417 16616-16616/com.arriva.debug W/System.err:     at android.os.Looper.loop(Looper.java:313)
2023-01-24 00:13:53.417 16616-16616/com.arriva.debug W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:8663)
2023-01-24 00:13:53.417 16616-16616/com.arriva.debug W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2023-01-24 00:13:53.417 16616-16616/com.arriva.debug W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
2023-01-24 00:13:53.417 16616-16616/com.arriva.debug W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135) 
```

**Comment by sshropshire** [comment]
@rohitgarg29 can you share a code snippet of your integration and verify that you are instantiating `DropInClient` in `onCreate()`?

**Comment by rohitgarg29** [comment]
Hi @sshropshire 

`override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        TealiumTracker.ctaViewBasket()
        TealiumTracker.checkout(
            EVENT_CHECKOUT_OPEN_STEP_NUMBER,
            EVENT_STEP_TITLE
        )
        ExponeaTracker.checkout(
            EVENT_CHECKOUT_OPEN_STEP_NUMBER,
            EVENT_STEP_TITLE
        )

        journeyHolder.apply {
            showTitle(true)
            title = getString(R.string.payment)
        }

        setUpTicketsAdapter()
        setUpViewPagerWithTabLayout()
        setUpViewPagerAdapter()
        setClickListeners()
        viewModel.clearPaymentToken()
        viewModel.isUserGuest()
        viewModel.listenUserLogin()
        viewModel.listenUserSignUp()
        viewModel.getPassengerTypes()

        dropInClient = DropInClient(this, this)
        dropInClient.setListener(this)
    }`

 ```
override fun getClientToken(callback: ClientTokenCallback) {
        callback.onSuccess(authenticationToken)
    }
```

**Comment by rohitgarg29** [comment]
Hi @scannillo 

```
<activity
            android:name="com.bus.payment.checkoutflow.ui.CheckoutActivity"
            android:label="@string/app_name"
            android:screenOrientation="portrait"
            android:exported="false"
            android:theme="@style/SearchJourneyTheme" />
```

**Comment by sshropshire** [comment]
@rohitgarg29 Can you take a look at the [manifest merger](https://developer.android.com/studio/build/manage-manifests#inspect_the_merged_manifest_and_find_conflicts) for your app and see what the final `android:scheme` value is for `DropInActivity`?

**Comment by rohitgarg29** [comment]
@sshropshire its value is `android:scheme = com.company.debug.braintree`

**Comment by sshropshire** [comment]
@rohitgarg29 thank you. That looks fine.

Can you update your client token provider to make sure authorization is not null?

Example:
```kotlin
override fun getClientToken(callback: ClientTokenCallback) {
  callback.onSuccess(requireNotNull(authenticationToken))
}
```

**Comment by rohitgarg29** [comment]
@sshropshire I did the same as you suggested, it is still same.

**Comment by sshropshire** [comment]
@rohitgarg29 the only scenario I can think of where DropIn cancels before displaying any UI is if the authorization is invalid. Can you provide a video reproducing the error in your app to help provide more context?

**Comment by rohitgarg29** [comment]
@sshropshire I was thinking that it should work with sandbox authorization string like demo, should I try that?

**Comment by sshropshire** [comment]
@rohitgarg29 you can either a tokenization key or a client token will work, although if you're using a tokenization key you can  use the `DropInClient(this, "<TOKENIZATION_KEY>")` constructor and won't need a `ClientTokenProvider` since it is already synchronously available to you.

**Comment by rohitgarg29** [comment]
@sshropshire i am trying in this way now

1.) Below code is in onCreate()
```
dropInClient = DropInClient(this, "sandbox_tmxhyf7d_dcpspy2brwdjr3qn")
dropInClient.setListener(this)
```

2. I have removed the callback

But i am still getting the same error.

**Comment by bendoddvista** [comment]
We had a problem with this.

I solved it in two ways.

1. When you launch the DropIn, recreate the dropInSubject to clear any current/historical error messages. EG: dropSubject = PublishSubject.create();
2. When you handle the Error, you need to ignore it for UserCanceledException. It's not really an exception. In our example, a user just clicked out of the bounds of the fragment.

**Comment by hollabaq86** [comment]
@rohitgarg29 did @bendoddvista's suggestion resolve your issue?

**Comment by rohitgarg29** [comment]
@hollabaq86 I was able to resolve it using the solution provided in #379 . Thanks for the help.
