### ISSUE TITLE
Drop in Crash Android 9

### ISSUE THREAD

**Issue by skauss** [braintree/braintree-android-drop-in#403]
**Integration Details (please complete the following information):**

* SDK/Library version: com.braintreepayments.api:drop-in:6.7.0
* Environment: Produktion
* Android Version and Device: Android 9 on GCE x86 phone and Pixel 6
* Braintree dependencies:
    implementation 'com.braintreepayments.api:drop-in:6.7.0'

**Describe the bug**
Crashlytics crash

```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void android.os.Bundle.setClassLoader(java.lang.ClassLoader)' on a null object reference
       at com.braintreepayments.api.DropInActivity.getDropInRequest(DropInActivity.java:123)
       at com.braintreepayments.api.DropInActivity.onCreate(DropInActivity.java:77)
       at android.app.Activity.performCreate(Activity.java:8050)
       at android.app.Activity.performCreate(Activity.java:8030)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3608)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7839)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

```
**To Reproduce**
This is an stacktrace found in crashlytics in production at our customer.

Regards
Stephan

**Comment by sshropshire** [comment]
@skauss thanks for your patience and for filing this issue. Do you happen to have analytics on how often this occurs? Also were you able to reproduce on an Android 9 emulator and have the repro steps?

**Comment by hollabaq86** [comment]
dropping due to inactivity, but if the issue still persists let us know the info @sshropshire asked for and we can re-open the issue!
