### ISSUE TITLE
Adding drop in dependency causing crash

### ISSUE THREAD

**Issue by VanishaGaba** [braintree/braintree-android-drop-in#404]
I am using  'com.braintreepayments.api:paypal:4.26.0' for adding payPal as payment method, but for other options I need drop in UI, If I add "com.braintreepayments.api:drop-in:6.8.0" dependency , now on clicking back from paypal screen app crashes with bug as 
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.henceforth.wardrobe, PID: 10527
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.henceforth.wardrobe/com.braintreepayments.api.DropInActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.os.Bundle.setClassLoader(java.lang.ClassLoader)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4166)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4312)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2571)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8741)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.os.Bundle.setClassLoader(java.lang.ClassLoader)' on a null object reference
        at com.braintreepayments.api.DropInActivity.getDropInRequest(DropInActivity.java:123)
        at com.braintreepayments.api.DropInActivity.onCreate(DropInActivity.java:77)
        at android.app.Activity.performCreate(Activity.java:8578)
        at android.app.Activity.performCreate(Activity.java:8557)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4147)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4312) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2571) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:226) 
        at android.os.Looper.loop(Looper.java:313) 
        at android.app.ActivityThread.main(ActivityThread.java:8741) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067) 
I/Process: Sending signal. PID: 10527 SIG: 9

**Comment by sshropshire** [comment]
Hi @VanishaGaba thanks for using the Braintree SDK for Android. Is this a problem on Android 9 only? We've recently received a similar issue https://github.com/braintree/braintree-android-drop-in/issues/403 and I want to confirm additional details about your scenario to try and reproduce the error.

**Comment by VanishaGaba** [comment]
No this issue is rising on Android 12 and in development phase. I have integrated paypal method when clicked on Proceed with sandbox purchase button app crashes if I add drop in dependency(com.braintreepayments.api:drop-in:6.7.0) . It works fine If I remove this dependency.

**Comment by sshropshire** [comment]
@VanishaGaba does the same unexpected behavior occur on both an emulator and a physical device?

**Comment by hollabaq86** [comment]
closing due to inactivity, but if you're still seeing this problem let us know and we can re-open it!

**Comment by rajatsharma16** [comment]
We do see this occassionally in our app's launch flow somewhere. Looks like it is produced by automation tests from Google performed once the app is uploaded. [The user email seems to be of type _something@cloudtestlabaccounts.com_]

**sdk version**: com.braintreepayments.api:drop-in:6.9.0

```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void android.os.Bundle.setClassLoader(java.lang.ClassLoader)' on a null object reference
       at com.braintreepayments.api.DropInActivity.getDropInRequest(DropInActivity.java:124)
       at com.braintreepayments.api.DropInActivity.onCreate(DropInActivity.java:78)
       at android.app.Activity.performCreate(Activity.java:7136)
       at android.app.Activity.performCreate(Activity.java:7127)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
       at androidx.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:2)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
```

**Comment by BunnyBuddy** [comment]
> I got java.lang.NullPointerException in Firebase Crashletics. sdk version: com.braintreepayments.api:drop-in:6.16.0 play-services-wallet version: com.google.android.gms:play-services-wallet:19.4.0
> 
> Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.app.inmatephotos/com.braintreepayments.api.DropInActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.os.Bundle.setClassLoader(java.lang.ClassLoader)' on a null object reference at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3635) at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792) at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103) at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210) at android.os.Handler.dispatchMessage(Handler.java:106) at android.os.Looper.loopOnce(Looper.java:201) at android.os.Looper.loop(Looper.java:288) at android.app.ActivityThread.main(ActivityThread.java:7839) at java.lang.reflect.Method.invoke(Method.java) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
> 
> Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void android.os.Bundle.setClassLoader(java.lang.ClassLoader)' on a null object reference at com.braintreepayments.api.DropInActivity.getDropInRequest(DropInActivity.java:124) at com.braintreepayments.api.DropInActivity.onCreate(DropInActivity.java:78) at android.app.Activity.performCreate(Activity.java:8050) at android.app.Activity.performCreate(Activity.java:8030) at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329) at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3608) at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792) at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103) at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210) at android.os.Handler.dispatchMessage(Handler.java:106) at android.os.Looper.loopOnce(Looper.java:201) at android.os.Looper.loop(Looper.java:288) at android.app.ActivityThread.main(ActivityThread.java:7839) at java.lang.reflect.Method.invoke(Method.java) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
> 
> ```
>     Effected Device & OS version listed below:-
>     1) Sdk_gphone_arm64 OS 11
>     2) Pixel 6  OS 12
>     3) GCE X86 Phone OS 9
>     4) TCL 30 Z OS 12
> ```

same here, I've got,

D/AndroidRuntime( 5012): Shutting down VM
E/AndroidRuntime( 5012): FATAL EXCEPTION: main
E/AndroidRuntime( 5012): Process: com.abcd.app, PID: 5012
E/AndroidRuntime( 5012): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.abcd.app/com.braintreepayments.api.DropInActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.os.Bundle.setClassLoader(java.lang.ClassLoader)' on a null object reference
E/AndroidRuntime( 5012): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3782)
E/AndroidRuntime( 5012): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3922)
E/AndroidRuntime( 5012): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
E/AndroidRuntime( 5012): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
E/AndroidRuntime( 5012): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
E/AndroidRuntime( 5012): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
E/AndroidRuntime( 5012): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 5012): 	at android.os.Looper.loopOnce(Looper.java:205)
E/AndroidRuntime( 5012): 	at android.os.Looper.loop(Looper.java:294)
E/AndroidRuntime( 5012): 	at android.app.ActivityThread.main(ActivityThread.java:8177)
E/AndroidRuntime( 5012): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 5012): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/AndroidRuntime( 5012): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
E/AndroidRuntime( 5012): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.os.Bundle.setClassLoader(java.lang.ClassLoader)' on a null object reference
E/AndroidRuntime( 5012): 	at com.braintreepayments.api.DropInActivity.getDropInRequest(DropInActivity.java:124)
E/AndroidRuntime( 5012): 	at com.braintreepayments.api.DropInActivity.onCreate(DropInActivity.java:78)
E/AndroidRuntime( 5012): 	at android.app.Activity.performCreate(Activity.java:8595)
E/AndroidRuntime( 5012): 	at android.app.Activity.performCreate(Activity.java:8573)
E/AndroidRuntime( 5012): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
E/AndroidRuntime( 5012): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3764)
E/AndroidRuntime( 5012): 	... 12 more
D/TrafficStats( 5012): tagSocket(89) with statsTag=0xffffffff, statsUid=-1
D/TrafficStats( 5012): tagSocket(77) with statsTag=0xffffffff, statsUid=-1
I/Process ( 5012): Sending signal. PID: 5012 SIG: 9


This seems to be the case on (only) Android 14 and above. 
The loader keeps loading and this but is thrown. 

Can you please urgently fix the issue or let us know a quick solution to this because the user can't pay via PayPal right now.

**Comment by 54lazycat** [comment]
same issue. version 6.15.0
