### ISSUE TITLE
Layout and Inflate Errors

### ISSUE THREAD

**Issue by sawyermade** [braintree/braintree-android-drop-in#418]
### Braintree SDK Version

6.9.0

### Environment

Sandbox

### Android Version & Device

Samsung S21 Ultra - Android 12

### Braintree dependencies

implementation 'com.braintreepayments.api:drop-in:6.9.0'

### Describe the bug

Once the drop in loads, the PayPal works fine and I can get the nonce but when clicking Credit or Debit Card it immediately crashes. This is the error I get:

FATAL EXCEPTION: main
Process: com.sjursolutions.videoinspectionprodev, PID: 8250
android.view.InflateException: Binary XML file line #32 in com.sjursolutions.videoinspectionprodev:layout/bt_fragment_add_card: Binary XML file line #32 in com.sjursolutions.videoinspectionprodev:layout/bt_fragment_add_card: Error inflating class com.braintreepayments.cardform.view.CardForm
Caused by: android.view.InflateException: Binary XML file line #32 in com.sjursolutions.videoinspectionprodev:layout/bt_fragment_add_card: Error inflating class com.braintreepayments.cardform.view.CardForm
Caused by: java.lang.reflect.InvocationTargetException
    at java.lang.reflect.Constructor.newInstance0(Native Method)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
    at android.view.LayoutInflater.createView(LayoutInflater.java:858)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
    at com.braintreepayments.api.AddCardFragment.onCreateView(AddCardFragment.java:50)
    at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2995)
    at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:523)
    at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
    at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
    at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1758)
    at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701)
    at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:488)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:226)
    at android.os.Looper.loop(Looper.java:313)
    at android.app.ActivityThread.main(ActivityThread.java:8582)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:563)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
Caused by: android.view.InflateException: Binary XML file line #9 in com.sjursolutions.videoinspectionprodev:layout/bt_card_form_fields: Binary XML file line #9: You must supply a layout_width attribute.
Caused by: java.lang.UnsupportedOperationException: Binary XML file line #9: You must supply a layout_width attribute.
    at android.content.res.TypedArray.getLayoutDimension(TypedArray.java:831)
    at android.view.ViewGroup$LayoutParams.setBaseAttributes(ViewGroup.java:9230)
    at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:9428)
    at android.widget.LinearLayout$LayoutParams.<init>(LinearLayout.java:2023)
    at android.widget.LinearLayout.generateLayoutParams(LinearLayout.java:1917)
    at android.widget.LinearLayout.generateLayoutParams(LinearLayout.java:89)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:1129)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:660)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:485)
    at android.view.View.inflate(View.java:28455)
    at com.braintreepayments.cardform.view.CardForm.init(CardForm.java:125)
    at com.braintreepayments.cardform.view.CardForm.<init>(CardForm.java:107)
    at java.lang.reflect.Constructor.newInstance0(Native Method)

### To reproduce

Tap Credit or Debit Card and it crashes

### Expected behavior

Should load the credit or debit card form

**Comment by sshropshire** [comment]
Hi @sawyermade thanks for using the Braintree SDK for Android. I'm trying to reproduce this error but I'm having trouble on a Pixel 6 Pro and a Galaxy S21 5G. Using the same steps to reproduce, does this same crash occur on another device / emulator?

**Comment by sawyermade** [comment]
No I haven't, I can try that though. Quick question though, why would the PayPal load just fine but the CC doesn't? Isn't that kind of strange? I did start a brand new app with only the drop in and it worked fine. The Gradle was setup the same as well. It's just strange that only CC does it? But yeah, I will check with other devices later, I wasn't sure if this was a known problem with a quick workaround, thanks for the response and I will get back to you once I try it on something else.

**Comment by sshropshire** [comment]
@sawyermade awesome thanks! For the PayPal flow we use a Chrome custom tab, so there isn't as much View inflation happening in that flow. Our DropIn library depends on another library we maintain called [android-card-form](https://github.com/braintree/android-card-form) and `CardForm` is a custom view. I checked those xml files and the width attributes are definitely set.

We haven't seen any issues with android-card-form lately, but we'll keep an eye out. If you have additional information, feel free to reach out and we'll take a look.

**Comment by sawyermade** [comment]
@sshropshire  I'll have some different devices later this afternoon but in the meantime, here's the activity that calls the drop in (I removed all the misc buttons and text that don't matter) but is there anything you can see from the layout that would cause that error? I don't know the card form as well, it may be something stupid from the calling activity layout I overlooked. Thanks again and let me know if anything stands out I should add/remove and will let you know when I try on another device. The btnPaymentSave launches the drop in...

```
<?xml version="1.0" encoding="utf-8"?>

<ScrollView
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/grayBackground">

    <androidx.constraintlayout.widget.ConstraintLayout 
        xmlns:tools="http://schemas.android.com/tools"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        tools:context=".PaymentActivity">

    <Button
        android:id="@+id/btnPaymentSave"
        android:layout_width="300dp"
        android:layout_height="wrap_content"
        android:layout_marginStart="8dp"
        android:layout_marginTop="40dp"
        android:layout_marginEnd="8dp"
        android:background="@drawable/rounded_button_green"
        android:backgroundTint="@color/clrDarkTerraCotta"
        android:text="@string/btnPaymentSave"
        android:textAllCaps="false"
        android:textColor="#FFFFFF"
        android:textSize="16sp"
        android:textStyle="normal"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintHorizontal_bias="0.494"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/lblPaymentCCN" />

    </androidx.constraintlayout.widget.ConstraintLayout>
</ScrollView>
```

**Comment by sshropshire** [comment]
@sawyermade nothing stands out as out of place. Technically your layout shouldn't affect the presentation of DropIn since it's contained in its own `Activity` and has its own view. I'd try it on another device or emulator just to make sure.

**Comment by sawyermade** [comment]
So I tried on an LG with android v9 and still get the same identical error. Min api is v24 and target is v33. Could the min be a problem?

**Comment by sshropshire** [comment]
@sawyermade interesting I can't say that I have. We have an import statement in [AddCardFragment.java](https://github.com/braintree/braintree-android-drop-in/blob/ba342f08e0bb2ed7865fb937f14b45e00481722b/Drop-In/src/main/java/com/braintreepayments/api/AddCardFragment.java#L14) that references the `R` class generated by the DropIn library.

Out of curiosity if you repeat the steps to reproduce on an emulator, does it work as expected?

**Comment by sawyermade** [comment]
I will test it out, but yeah that import was "R" method part of it was red. The import only the R is red in android studio (Cannot resolve symbol R): import com.braintreepayments.api.dropin.R; Its really weird but yeah, I will try it on the emulator tmr and get back to you. Thanks for the help!

**Comment by sawyermade** [comment]
Yeah, same thing. I also had my coworker run it off his windows PC (im on Mac and linux) with his v9 android and same stuff. Super weird the R isn't resolved, right?

**Comment by sshropshire** [comment]
@sawyermade are y'all using proguard in your project? And to confirm it's the same behavior when using an emulator?

**Comment by sawyermade** [comment]
We are using proguard, which version emulator should I try using? I believe I was using an older v9 android emulator. Here is the proguard in the Gradle app section in the android {}:
```
buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
```

**Comment by jaxdesmarais** [comment]
Closing this issue due to inactivity, please open a new issue if you are still running into errors. Please note, the Drop-in SDK is now in an [inactive status](https://developer.paypal.com/braintree/docs/guides/client-sdk/deprecation-policy/android/v5/#status-categories) and will not be receiving further enhancements. Starting September 1, 2026 the Drop-in SDK will move to a [deprecated status](https://developer.paypal.com/braintree/docs/guides/client-sdk/deprecation-policy/android/v5/#status-categories) and we will no longer make any updates to this SDK. Processing will be supported for 1 year after the deprecation date, but you should upgrade immediately to avoid any disruption.

Starting September 1, 2027 the Drop-in SDK will move to an [unsupported status](https://developer.paypal.com/braintree/docs/guides/client-sdk/deprecation-policy/android/v5/#status-categories) and will no longer supported by Braintree developers or Braintree Support. Processing for unsupported SDKs can be suspended at any time.

Please migrate to the [Braintree SDK](https://github.com/braintree/braintree_android) to continue processing and receiving updates.
