### ISSUE TITLE
Attempt to read from field 'java.lang.String com.cardinalcommerce.a.td.d'

### ISSUE THREAD

**Issue by mionescu95** [braintree/braintree-android-drop-in#427]
### Braintree SDK Version

6.8.0

### Environment

Sandbox

### Braintree dependencies

api 'com.braintreepayments.api:drop-in:6.8.0'

### Describe the bug

Hi, we have found some crashes in logs with some not very helpful description. Is is possible that we may miss something?

Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.cardinalcommerce.a.td.d' on a null object reference in method 'void com.cardinalcommerce.a.mg.f(com.cardinalcommerce.a.we, com.cardinalcommerce.a.oj, java.lang.String)'
       at com.cardinalcommerce.a.setCompoundDrawableTintMode.init(:2082)
       at com.cardinalcommerce.a.setTextSelectHandleRight.CardinalRenderType(:40597)
       at com.cardinalcommerce.a.setTextSelectHandleRight$8.onClick(:421)
       at android.view.View.performClick(View.java:7892)
       at android.widget.TextView.performClick(TextView.java:16219)
       at android.view.View.performClickInternal(View.java:7869)
       at android.view.View.-$$Nest$mperformClickInternal()
       at android.view.View$PerformClick.run(View.java:30880)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8757)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

### To reproduce

We don't really have steps as it's a sometimes issue only observed in logs.

### Expected behavior

It should not be an error.

**Comment by sshropshire** [comment]
Hi @mionescu95 thanks for using our Drop In library. I would make sure your app is including the latest [6.11.0](https://github.com/braintree/braintree-android-drop-in/blob/master/CHANGELOG.md#6110) version. This version contains the latest Cardinal version as well. The null pointer exception mentioned here may have been resolved.

**Comment by hollabaq86** [comment]
going to close this issue since we haven't heard from OP.
