### ISSUE TITLE
Unable to register DropInClient within coroutines or suspend functions or view model

### ISSUE THREAD

**Issue by AG-Akash09** [braintree/braintree-android-drop-in#467]
### Braintree SDK Version

6.15.0

### Environment

Both

### Braintree dependencies

    implementation 'com.braintreepayments.api:drop-in:6.15.0'
    implementation 'com.braintreepayments.api:data-collector:4.41.0'

### Describe the bug

Our network calls are seamlessly integrated with coroutines and view models. To retrieve the client token from our server, we employ a suspend function and observe its value in the onCreateView function. However, attempting to pass the client token to DropInClient results in a crash, accompanied by the error 'java.lang.IllegalStateException: LifecycleOwner MembershipFragment is attempting to register while current state is RESUMED. LifecycleOwners must call register before they are STARTED.' Although registering directly with the DropInClient within onCreateView using the tokenization key works flawlessly, we're constrained by the tokenization key's limitations, necessitating our reliance on the client token exclusively.

### To reproduce

Code Snippet
viewModel.paymentToken.observe(viewLifecycleOwner, Observer {
            Log.d("Payment Token ","$it")
            val fragmentActivity = requireActivity();
            dropInClient = DropInClient(fragmentActivity,it)
            val dropInRequest = DropInRequest()

            dropInRequest.cardholderNameStatus = CardForm.FIELD_REQUIRED
            dropInRequest.maskSecurityCode = true
            dropInClient.launchDropIn(dropInRequest)
        })

### Expected behavior

DropInClient should registered successfully

### Screenshots

<img width="972" alt="Screenshot 2024-03-26 at 9 08 21 PM" src="https://github.com/braintree/braintree-android-drop-in/assets/67047940/f5edfffa-2bec-491a-a4ca-c8c96b1e241c">

**Comment by warmkesselj** [comment]
Hey @AG-Akash09, thanks for the message. We’re aware of limitations with the current constructor and would need to make a breaking change to truly resolve this issue. We may investigate this further and publish a long term fix as part of a beta release of our next major version but this is not on our current roadmap.

In the meantime, the following workaround strategy may work:

```
        paymentToken.observe(viewLifecycleOwner, {
            Log.d("Payment Token", it)

            val clientTokenProvider = ClientTokenProvider { callback ->
                viewModel.paymentToken.observe(viewLifecycleOwner, {
                    callback.onSuccess(it)
                }
            }
            dropInClient = DropInClient(fragmentActivity, clientTokenProvider)
        })
```

**Comment by AG-Akash09** [comment]
Thanks for your active response. I have tried the workaround strategy, but still the same issue is encountered, i.e. 
"java.lang.IllegalStateException: LifecycleOwner com.andateknoloji.apps.nybox.MainActivity@d5a363d is attempting to register while current state is RESUMED. LifecycleOwners must call register before they are STARTED.
                                                                                                    	at androidx.activity.result.ActivityResultRegistry.register(ActivityResultRegistry.java:123)
                                                                                                    	at com.braintreepayments.api.DropInLifecycleObserver.onCreate(DropInLifecycleObserver.java:30)
                                                                                                    	at androidx.lifecycle.FullLifecycleObserverAdapter.onStateChanged(FullLifecycleObserverAdapter.java:36)
                                                                                                    	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:360)
                                                                                                    	at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:202)
                                                                                                    	at com.braintreepayments.api.DropInClient.addObserver(DropInClient.java:187)
                                                                                                    	at com.braintreepayments.api.DropInClient.<init>(DropInClient.java:181)
                                                                                                    	at com.braintreepayments.api.DropInClient.<init>(DropInClient.java:140)"
<img width="1015" alt="Screenshot 2024-03-27 at 10 27 29 AM" src="https://github.com/braintree/braintree-android-drop-in/assets/67047940/5c295e1c-b009-4b0c-bc1d-b30842bde7fa">

**Comment by warmkesselj** [comment]
@AG-Akash09 can you try removing the outer ```viewModel.paymentToken.observe(viewLifecycleOwner, ```

**Comment by sjqnice** [comment]
I use it in compose with the same IllegalStateException, have you resolve it?

**Comment by jaxdesmarais** [comment]
Closing due to inactivity. Please open a new issue if you still need assistance. Please also note, the Drop-in SDK is now in an [inactive status](https://developer.paypal.com/braintree/docs/guides/client-sdk/deprecation-policy/android/v5/#status-categories). Starting September 1, 2026 the Drop-in SDK will move to a [deprecated status](https://developer.paypal.com/braintree/docs/guides/client-sdk/deprecation-policy/android/v5/#status-categories) and we will no longer make any updates to this SDK. Processing will be supported for 1 year after the deprecation date, but you should upgrade immediately to avoid any disruption.

Starting September 1, 2027 the Drop-in SDK will move to an [unsupported status](https://developer.paypal.com/braintree/docs/guides/client-sdk/deprecation-policy/android/v5/#status-categories) and will no longer supported by Braintree developers or Braintree Support. Processing for unsupported SDKs can be suspended at any time.

Please migrate to the [Braintree SDK](https://github.com/braintree/braintree_android) to continue processing and receiving updates.
