### ISSUE TITLE
Crash in braintree

### ISSUE THREAD

**Issue by maidt2212** [braintree/braintree-android-drop-in#470]
### Braintree SDK Version

6.15.0

### Environment

Production

### Android Version & Device

Vivo X70 android 14

### Braintree dependencies

com.braintreepayments.api:drop-in:6.15.0
com.google.android.gms:play-services-wallet:16.0.0

### Describe the bug

Crash occurs:
Fatal Exception: java.lang.IllegalStateException: Attempting to launch an unregistered ActivityResultLauncher with contract com.braintreepayments.api.k8@85aef4c and input com.braintreepayments.api.s8@4693b95. You must ensure the ActivityResultLauncher is registered before calling launch().
       at androidx.activity.result.ActivityResultRegistry$a.b(ActivityResultRegistry.java:6)
       at androidx.activity.result.ActivityResultLauncher.a(:1)
       at com.braintreepayments.api.ThreeDSecureLifecycleObserver.a(:2)
       at com.braintreepayments.api.m8.v(ThreeDSecureClient.java:16)
       at com.braintreepayments.api.m8.e()
       at com.braintreepayments.api.m8$e.a(:11)
       at com.braintreepayments.api.x0.t(BraintreeClient.kt:1)
       at com.braintreepayments.api.x0.c()
       at com.braintreepayments.api.w0.a(:2)
       at com.braintreepayments.api.m2.c(ConfigurationLoader.kt:10)
       at com.braintreepayments.api.x0.s(BraintreeClient.kt:1)
       at com.braintreepayments.api.x0.i()
       at com.braintreepayments.api.n0.a(:4)
       at com.braintreepayments.api.w.b(AuthorizationLoader.kt:2)
       at com.braintreepayments.api.x0.o(:7)
       at com.braintreepayments.api.x0.r(:10)
       at com.braintreepayments.api.m8.i(:13)
       at com.braintreepayments.api.m8.h(:5)
      

### To reproduce

I just add credit card to payment

### Expected behavior

No crash

**Comment by sshropshire** [comment]
Hi @maidt2212 can you provide more information on how to reproduce this issue? Also as a test, does it work when `minifyEnabled` is set to `false` in your app's build.gradle?

**Comment by maidt2212** [comment]
Hi @sshropshire Actually we cannot reproduce it. I see this crash from firebase crashlytic. Let me add minifyEnabled and observe it. Thank you

**Comment by sshropshire** [comment]
@maidt2212 ok got it thank you. I mention that only because the stack trace appears minified. I wonder if the obfuscation process might cause a bug somehow.

**Comment by maidt2212** [comment]
Hi @sshropshire We refer implementation from this source https://github.com/pikaju/flutter-braintree So Can you check if it have any issue?

**Comment by sshropshire** [comment]
@maidt2212 we actually don't own that repo. We don't offer official support for Flutter at the moment. Can you file an issue with [pikaju/flutter-braintree](https://github.com/pikaju/flutter-braintree/issues) and let us know if you have additional information?

**Comment by maidt2212** [comment]
Hi @sshropshire Sorry for remind again, But can you please help to check in braintree lib? Although this lib is used in flutter app but we implement it as native code and integrate. So as you see the crash occur in native android code of braintree.

**Comment by jaxdesmarais** [comment]
Closing due to inactivity, please open a new issue if you are still running into errors. Please also note, the Drop-in SDK is now in an [inactive status](https://developer.paypal.com/braintree/docs/guides/client-sdk/deprecation-policy/android/v5/#status-categories). Starting September 1, 2026 the Drop-in SDK will move to a [deprecated status](https://developer.paypal.com/braintree/docs/guides/client-sdk/deprecation-policy/android/v5/#status-categories) and we will no longer make any updates to this SDK. Processing will be supported for 1 year after the deprecation date, but you should upgrade immediately to avoid any disruption.

Starting September 1, 2027 the Drop-in SDK will move to an [unsupported status](https://developer.paypal.com/braintree/docs/guides/client-sdk/deprecation-policy/android/v5/#status-categories) and will no longer supported by Braintree developers or Braintree Support. Processing for unsupported SDKs can be suspended at any time.

Please migrate to the [Braintree SDK](https://github.com/braintree/braintree_android) to continue processing and receiving updates.
