### ISSUE TITLE
NullPointerException in TLSCertificatePinning.getCertInputStream

### ISSUE THREAD

**Issue by hankyjcheng** [braintree/braintree-android-drop-in#477]
### Braintree SDK Version

6.16.0

### Environment

Production

### Braintree dependencies

com.braintreepayments.api:drop-in:6.16.0
com.braintreepayments.api:braintree-core:4.45.0

### Describe the bug

This crash is captured on Firebase Crashlytics:

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] java.lang.String.getBytes(java.nio.charset.Charset)' on a null object reference
       at com.braintreepayments.api.TLSCertificatePinning.getCertInputStream(TLSCertificatePinning.java:719)
       at com.braintreepayments.api.BraintreeGraphQLClient$Companion.createDefaultHttpClient(BraintreeGraphQLClient.java:82)
       at com.braintreepayments.api.BraintreeGraphQLClient$Companion.access$createDefaultHttpClient(BraintreeGraphQLClient.java:79)
       at com.braintreepayments.api.BraintreeGraphQLClient.<init>(BraintreeGraphQLClient.kt:6)
       at com.braintreepayments.api.BraintreeClientParams.<init>(BraintreeClientParams.kt:13)
       at com.braintreepayments.api.BraintreeClientParams.<init>(BraintreeClientParams.kt:22)
       at com.braintreepayments.api.BraintreeClient.<init>(BraintreeClient.kt:70)
       at com.braintreepayments.api.DropInClient.createDefaultParams(DropInClient.java:50)
       at com.braintreepayments.api.DropInClient.<init>(DropInClient.java:163)

### To reproduce

not reproducible by dev

### Expected behavior

Should not have a crash

**Comment by sshropshire** [comment]
Hey @hankyjcheng thanks for using the Braintree SDK for Android and for filing this. Do you have any additional information about the environment in which the crash occurred e.g. Device Name, Device Manufacturer etc.?

**Comment by ersen-lw** [comment]
Hello, 

I got a crash report with the same issue a few days ago.

Using `com.braintreepayments.api:drop-in:6.16.0` 

The crash also occurred on Android 14.  

```
          Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] java.lang.String.getBytes(java.nio.charset.Charset)' on a null object reference
       at com.braintreepayments.api.TLSCertificatePinning.getCertInputStream(TLSCertificatePinning.java:719)
       at com.braintreepayments.api.BraintreeHttpClient$Companion.createDefaultHttpClient(BraintreeHttpClient.java:178)
       at com.braintreepayments.api.BraintreeHttpClient$Companion.access$createDefaultHttpClient(BraintreeHttpClient.java:172)
       at com.braintreepayments.api.BraintreeHttpClient.<init>(BraintreeHttpClient.kt:12)
       at com.braintreepayments.api.AnalyticsClient.<init>(AnalyticsClient.java:25)
       at com.braintreepayments.api.BraintreeClientParams.<init>(BraintreeClientParams.java:14)
       at com.braintreepayments.api.BraintreeClientParams.<init>(BraintreeClientParams.java:22)
       at com.braintreepayments.api.BraintreeClient.<init>(BraintreeClient.kt:70)
       at com.braintreepayments.api.DropInClient.createDefaultParams(DropInClient.java:50)
       at com.braintreepayments.api.DropInClient.<init>(DropInClient.java:163)
```

<img width="580" alt="image" src="https://github.com/user-attachments/assets/4ce53dff-6b37-465d-950c-0e981155559b">

**Comment by BunnyBuddy** [comment]
Even in other issues I see `java.lang.NullPointerException` mostly in Android 14 and it seems some package or plugin being used by Braintree has some issues with Android 14. Because the same things are working fine on Android 13 and Android 15.

**Comment by PenguinDan** [comment]
Finding the same crashes on Android 14 devices

**Comment by jaxdesmarais** [comment]
Closing due to inactivity, please open a new issue if you are still running into errors. Please also note, the Drop-in SDK is now in an [inactive status](https://developer.paypal.com/braintree/docs/guides/client-sdk/deprecation-policy/android/v5/#status-categories). Starting September 1, 2026 the Drop-in SDK will move to a [deprecated status](https://developer.paypal.com/braintree/docs/guides/client-sdk/deprecation-policy/android/v5/#status-categories) and we will no longer make any updates to this SDK. Processing will be supported for 1 year after the deprecation date, but you should upgrade immediately to avoid any disruption.

Starting September 1, 2027 the Drop-in SDK will move to an [unsupported status](https://developer.paypal.com/braintree/docs/guides/client-sdk/deprecation-policy/android/v5/#status-categories) and will no longer supported by Braintree developers or Braintree Support. Processing for unsupported SDKs can be suspended at any time.

Please migrate to the [Braintree SDK](https://github.com/braintree/braintree_android) to continue processing and receiving updates.
