### ISSUE TITLE
App Crashes upon returning from browser while rotating the screen in landscape mode

### ISSUE THREAD

**Issue by yosrri** [braintree/braintree-android-drop-in#487]
### Braintree SDK Version

6.13.0 Drop in UI

### Environment

Sandbox

### Android Version & Device

samsng A52S Android 14

### Braintree dependencies

    implementation "com.braintreepayments.api:drop-in:6.13.0"

### Describe the bug

Upon opening paypal browser from the drop in, rotating the phone in landscape mode and successfully saving and continuing, the app crashes when i return to it from browser

 Process: com.mailbox.debug, PID: 13668
                                                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mailbox.debug/com.braintreepayments.api.DropInActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.os.Bundle.setClassLoader(java.lang.ClassLoader)' on a null object reference
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4164)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4322)
                                                                                                    	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:6499)
                                                                                                    	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:6378)
                                                                                                    	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:76)
                                                                                                    	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:230)
                                                                                                    	at android.os.Looper.loop(Looper.java:319)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8919)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
                                                                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.os.Bundle.setClassLoader(java.lang.ClassLoader)' on a null object reference
                                                                                                    	at com.braintreepayments.api.DropInActivity.getDropInRequest(DropInActivity.java:124)
                                                                                                    	at com.braintreepayments.api.DropInActivity.onCreate(DropInActivity.java:78)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8975)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8944)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4146)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4322) 
                                                                                                    	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:6499) 
                                                                                                    	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:6378) 
                                                                                                    	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:76) 
                                                                                                    	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:230) 
                                                                                                    	at android.os.Looper.loop(Looper.java:319) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8919) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103) 

### To reproduce

Open Drop in UI
Choose PayPal 
Rotate the phone in browser 
add credentials save and continue

### Expected behavior

that it shouldn't crash

**Comment by saperi22** [comment]
@yosrri Thanks for reporting this. We'll take a look at this and will let you know of any action we'll take.

**Comment by yosrri11** [comment]
@saperi22  A note to mention also that we lock orientation to portrait for Mobile phones while tablets can do orientation freely

**Comment by amijsul** [comment]
Any updates on this issue, I'm getting the same exception but on Android 14 phones every time I try to finish a paypal transaction in the webview. I found this issue and it seems like something deep is going on in the BT code where the Activity is not being reinstantiated after the webview returns.

**Comment by jaxdesmarais** [comment]
Closing due to inactivity, please open a new issue if you are still running into errors. Please also note, the Drop-in SDK is now in an [inactive status](https://developer.paypal.com/braintree/docs/guides/client-sdk/deprecation-policy/android/v5/#status-categories). Starting September 1, 2026 the Drop-in SDK will move to a [deprecated status](https://developer.paypal.com/braintree/docs/guides/client-sdk/deprecation-policy/android/v5/#status-categories) and we will no longer make any updates to this SDK. Processing will be supported for 1 year after the deprecation date, but you should upgrade immediately to avoid any disruption.

Starting September 1, 2027 the Drop-in SDK will move to an [unsupported status](https://developer.paypal.com/braintree/docs/guides/client-sdk/deprecation-policy/android/v5/#status-categories) and will no longer supported by Braintree developers or Braintree Support. Processing for unsupported SDKs can be suspended at any time.

Please migrate to the [Braintree SDK](https://github.com/braintree/braintree_android) to continue processing and receiving updates.
