### ISSUE TITLE
Google Pay, Crash

### ISSUE THREAD

**Issue by DuoBlood** [braintree/braintree-android-drop-in#59]
### General information

* SDK/Library version: 
-- BRAINTREE_VERSION = '2.8.1'
-- BRAINTREE_DROP_IN = '3.2.0'
-- BRAINTREE_COLLECTOR = '2.5.4'
-- PLAY_SERVICE_VERSION = '11.4.2'
* Environment: Sandbox
* Android Version and Device: Nexus 5 with Android 6.0.1

### Issue description

if add a special character to the `TransactionInfo.Builder.setTotalPrice` method after selecting the  "Google Pay" payment method it will will cause the app to crash but should return .

e.g.
```
private GooglePaymentRequest getGooglePaymentRequest() {
        return new GooglePaymentRequest()
                .transactionInfo(TransactionInfo.newBuilder()
                        .setTotalPrice("$1.00") // <-------------------HERE---------
                        .setTotalPriceStatus(WalletConstants.TOTAL_PRICE_STATUS_FINAL)
                        .setCurrencyCode("USD")
                        .build());
    }
```

* Logs:
`FATAL EXCEPTION: main
                                                                        Process: com.guzmanygomez.gyg.dev, PID: 9883
                                                                        java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = com.braintreepayments.api.exceptions.GooglePaymentException)
                                                                            at android.os.Parcel.writeSerializable(Parcel.java:1468)
                                                                            at android.os.Parcel.writeValue(Parcel.java:1416)
                                                                            at android.os.Parcel.writeArrayMapInternal(Parcel.java:686)
                                                                            at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1330)
                                                                            at android.os.Bundle.writeToParcel(Bundle.java:1079)
                                                                            at android.os.Parcel.writeBundle(Parcel.java:711)
                                                                            at android.content.Intent.writeToParcel(Intent.java:7793)
                                                                            at android.app.ActivityManagerProxy.finishActivity(ActivityManagerNative.java:2918)
                                                                            at android.app.Activity.finish(Activity.java:4873)
                                                                            at android.app.Activity.finish(Activity.java:4891)
                                                                            at com.braintreepayments.api.dropin.DropInActivity.finish(DropInActivity.java:372)
                                                                            at com.braintreepayments.api.dropin.BaseActivity.finish(BaseActivity.java:65)
                                                                            at com.braintreepayments.api.dropin.DropInActivity$4.onAnimationFinished(DropInActivity.java:194)
                                                                            at com.braintreepayments.api.dropin.DropInActivity$9.onAnimationEnd(DropInActivity.java:358)
                                                                            at android.view.animation.Animation$3.run(Animation.java:376)
                                                                            at android.os.Handler.handleCallback(Handler.java:739)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at android.os.Looper.loop(Looper.java:148)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                         Caused by: java.io.NotSerializableException: com.google.android.gms.common.api.Status
                                                                            at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1344)
                                                                            at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
                                                                            at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
                                                                            at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
                                                                            at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:959)
                                                                            at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:360)
                                                                            at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1054)
                                                                            at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1384)
                                                                            at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
                                                                            at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
                                                                            at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
                                                                            at android.os.Parcel.writeSerializable(Parcel.java:1463)
                                                                            at android.os.Parcel.writeValue(Parcel.java:1416) 
                                                                            at android.os.Parcel.writeArrayMapInternal(Parcel.java:686) 
                                                                            at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1330) 
                                                                            at android.os.Bundle.writeToParcel(Bundle.java:1079) 
                                                                            at android.os.Parcel.writeBundle(Parcel.java:711) 
                                                                            at android.content.Intent.writeToParcel(Intent.java:7793) 
                                                                            at android.app.ActivityManagerProxy.finishActivity(ActivityManagerNative.java:2918) 
                                                                            at android.app.Activity.finish(Activity.java:4873) 
                                                                            at android.app.Activity.finish(Activity.java:4891) 
                                                                            at com.braintreepayments.api.dropin.DropInActivity.finish(DropInActivity.java:372) 
                                                                            at com.braintreepayments.api.dropin.BaseActivity.finish(BaseActivity.java:65) 
                                                                            at com.braintreepayments.api.dropin.DropInActivity$4.onAnimationFinished(DropInActivity.java:194) 
                                                                            at com.braintreepayments.api.dropin.DropInActivity$9.onAnimationEnd(DropInActivity.java:358) 
                                                                            at android.view.animation.Animation$3.run(Animation.java:376) 
                                                                            at android.os.Handler.handleCallback(Handler.java:739) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                            at android.os.Looper.loop(Looper.java:148) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

**Comment by bluk** [comment]
The [`setTotalPrice`](https://developers.google.com/android/reference/com/google/android/gms/wallet/TransactionInfo.Builder.html#setTotalPrice(java.lang.String)) method only accepts strings that match the following regular expression `[0-9]+(\.[0-9][0-9])?`. Based on the regex, you would need to pass in `1.00` instead.

**Comment by DuoBlood** [comment]
Thanks, I have never read docs....

The problem is that [Status](https://developers.google.com/android/reference/com/google/android/gms/common/api/Status) is not `Serializable` and you try to put GooglePaymentException in extras (`#putExtra(String, Serializable)`) `com.braintreepayments.api.dropin.BaseActivity#finish(Exception)` `line 64`

**Comment by bluk** [comment]
You're right. The code should handle the error better. I've added this to our backlog to fix the error handling.
