### ISSUE TITLE
Google Pay payment method throws a ClassNotFoundException

### ISSUE THREAD

**Issue by artetrad** [braintree/braintree-android-drop-in#70]
### General information

* SDK/Library version: 3.3.0
* Environment: Sandbox 
* Android Version and Device: Samsung S5 mini(SM-G800F) with Android 6.0.1

### Issue description
I just updated the drop-in API from version 3.1.0 to 3.3.0, in order to support Google Pay in the DropIn menu as a payment method. I previously had used the custom intgration via BraintreeFragment which worked very well but I had to put the Google Pay button outside the dro-in UI.

After successfully showing the Google Pay option in the drop-in UI, I get a ClassNotFoundException when actually trying to complete the payment method selection. A message(dialog) pops up with the title "Request failed" and the message "An unexpected error has occured. Please try again later." along with the following stacktrace.

I am using the 'com.google.android.gms:play-services-wallet:11.4.0' and have included the wallet API as enabled in the AndroidManifest.xml. As I said the GooglePay was warking previously with the BraintreeFragment integration. 

Note: This is haoppening in debug and release builds regardless of Proguard.
```
03-22 14:52:38.872 2367-6293/? E/Parcel: Class not found when unmarshalling: com.braintreepayments.api.dropin.DropInRequest
                                         java.lang.ClassNotFoundException: com.braintreepayments.api.dropin.DropInRequest
                                             at java.lang.Class.classForName(Native Method)
                                             at java.lang.Class.forName(Class.java:324)
                                             at android.os.Parcel.readParcelableCreator(Parcel.java:2405)
                                             at android.os.Parcel.readParcelable(Parcel.java:2359)
                                             at android.os.Parcel.readValue(Parcel.java:2265)
                                             at android.os.Parcel.readArrayMapInternal(Parcel.java:2620)
                                             at android.os.BaseBundle.unparcel(BaseBundle.java:221)
                                             at android.os.BaseBundle.getString(BaseBundle.java:920)
                                             at android.content.Intent.getStringExtra(Intent.java:6228)
                                             at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:2746)
                                             at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:2210)
                                             at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:6632)
                                             at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:6368)
                                             at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:174)
                                             at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:4195)
                                             at android.os.Binder.execTransact(Binder.java:453)
                                          Caused by: java.lang.ClassNotFoundException: com.braintreepayments.api.dropin.DropInRequest
                                             at java.lang.Class.classForName(Native Method)
                                             at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                             at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                             at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                             at java.lang.Class.classForName(Native Method) 
                                             at java.lang.Class.forName(Class.java:324) 
                                             at android.os.Parcel.readParcelableCreator(Parcel.java:2405) 
                                             at android.os.Parcel.readParcelable(Parcel.java:2359) 
                                             at android.os.Parcel.readValue(Parcel.java:2265) 
                                             at android.os.Parcel.readArrayMapInternal(Parcel.java:2620) 
                                             at android.os.BaseBundle.unparcel(BaseBundle.java:221) 
                                             at android.os.BaseBundle.getString(BaseBundle.java:920) 
                                             at android.content.Intent.getStringExtra(Intent.java:6228) 
                                             at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:2746) 
                                             at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:2210) 
                                             at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:6632) 
                                             at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:6368) 
                                             at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:174) 
                                             at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:4195) 
                                             at android.os.Binder.execTransact(Binder.java:453) 
                                          Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
```

**Comment by artetrad** [comment]
I just tried the demo app that you provide and I get the same error.

**Comment by sdcoffey** [comment]
Hey @artetrad,

Thanks for the bug report. I'm not able to reproduce this on that version of Android specified. Are you able to reproduce this in emulators or real devices running other versions of Android?

**Comment by artetrad** [comment]
I just pulled the project to my work pc and everything is working. I was testing it on real devices and its now working in those as well. I am not sure why this happened, but we can close the issue for now. Thanks @sdcoffey

**Comment by sdcoffey** [comment]
Great, sometimes things like this can pop up because of weird build artifacts or other weirdness in the build. Let me know if it comes back with a noticable pattern.
