### ISSUE TITLE
Encrypted payload has expired

### ISSUE THREAD

**Issue by ericn37** [braintree/braintree-android-drop-in#8]
What is wrong?
```
E/BrainTreePaymentFlow: com.braintreepayments.api.exceptions.BrowserSwitchException: {"debug_id":null,"message":"Encrypted payload has expired"}
                            at com.braintreepayments.api.PayPal.onActivityResult(PayPal.java:389)
                            at com.braintreepayments.api.BraintreeFragment.onActivityResult(BraintreeFragment.java:329)
                            at com.braintreepayments.api.BraintreeFragment.onResume(BraintreeFragment.java:244)
                            at android.app.Fragment.performResume(Fragment.java:2263)
                            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1008)
                            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
                            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1130)
                            at android.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:1963)
                            at android.app.FragmentController.dispatchResume(FragmentController.java:174)
                            at android.app.Activity.performResume(Activity.java:6333)
                            at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3092)
                            at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3134)
                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1388)
                            at android.os.Handler.dispatchMessage(Handler.java:102)
                            at android.os.Looper.loop(Looper.java:148)
                            at android.app.ActivityThread.main(ActivityThread.java:5417)
                            at java.lang.reflect.Method.invoke(Native Method)
                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by sdcoffey** [comment]
Hey @ericn37 

Thanks for bringing this to our attention. There's a time limit between when a PayPal browser switch can be started and when we allow a transactable payload to be returned to your app. For instance, if a customer started paying with PayPal, left your app, and came back several hours later, and completed the flow, you'd get an error similar to this. 

Can you provide some more context around this error? Did it cause your app to crash?

**Comment by ericn37** [comment]
Hi @sdcoffey , my app didn't crash but the web browser fail to launch it exists itself immediately, making it impossible for the user to complete the payment

I've try initiating the checkout process again a few time but encounter this error every time

**Comment by sdcoffey** [comment]
Hmm, can you provide some more information about your integration? Are you using sandbox or production? What version of the BT SDK are you using?

**Comment by sdcoffey** [comment]
Hey @ericn37,

Just to follow up, it seems like there was a bug a few versions back where if your emulator's clock was 10ish minutes behind the actual time, you'll get an error like you described. You should try the newest version of `braintree_android` if you're not already doing so, and if you're using an emulator, restart or ensure that your emulator's clock is correct (sometimes they can get out of sync). If the issue remains, let me know and we'll take another look.

**Comment by sdcoffey** [comment]
@ericn37, I'm going to close this for now. Please let us know if it pops up again!
