### ISSUE TITLE
Facing a random crash for Drop in UI in android.

### ISSUE THREAD

**Issue by jadhavsuraj73** [braintree/braintree-android-drop-in#9]
FATAL EXCEPTION: main
android.view.InflateException: Binary XML file line #33: Error inflating class fragment
                                                                             at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:763)
                                                                             at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
                                                                             at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
                                                                             at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                                                                             at android.view.ViewStub.inflate(ViewStub.java:264)
                                                                             at com.braintreepayments.api.BraintreePaymentActivity$StubbedView.inflateOrFind(BraintreePaymentActivity.java:389)
                                                                             at com.braintreepayments.api.BraintreePaymentActivity$StubbedView.show(BraintreePaymentActivity.java:408)
                                                                             at com.braintreepayments.api.BraintreePaymentActivity.showAddPaymentMethodView(BraintreePaymentActivity.java:260)
                                                                             at com.braintreepayments.api.BraintreePaymentActivity$2$1.run(BraintreePaymentActivity.java:237)
                                                                             at android.os.Handler.handleCallback(Handler.java:739)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                             at android.os.Looper.loop(Looper.java:135)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5312)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:372)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
                                                                          Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.TypedArray android.app.Activity.obtainStyledAttributes(android.util.AttributeSet, int[])' on a null object reference
                                                                             at android.app.Fragment.onInflate(Fragment.java:1192)
                                                                             at android.app.FragmentManagerImpl.onCreateView(FragmentManager.java:2117)
                                                                             at android.app.Activity.onCreateView(Activity.java:5302)
                                                                             at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:733)
                                                                             at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
                                                                             at android.view.LayoutInflater.rInflate(LayoutInflater.java:809) 
                                                                             at android.view.LayoutInflater.rInflate(LayoutInflater.java:809) 
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
                                                                             at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
                                                                             at android.view.ViewStub.inflate(ViewStub.java:264) 
                                                                             at com.braintreepayments.api.BraintreePaymentActivity$StubbedView.inflateOrFind(BraintreePaymentActivity.java:389) 
                                                                             at com.braintreepayments.api.BraintreePaymentActivity$StubbedView.show(BraintreePaymentActivity.java:408) 
                                                                             at com.braintreepayments.api.BraintreePaymentActivity.showAddPaymentMethodView(BraintreePaymentActivity.java:260) 
                                                                             at com.braintreepayments.api.BraintreePaymentActivity$2$1.run(BraintreePaymentActivity.java:237) 
                                                                             at android.os.Handler.handleCallback(Handler.java:739) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                             at android.os.Looper.loop(Looper.java:135) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5312) 
                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                             at java.lang.reflect.Method.invoke(Method.java:372)

**Comment by quinnjn** [comment]
@jadhavsuraj73 Can you tell us what version you're running?

You should upgrade to `3+` when you can. Otherwise, you should upgrade to `2.3.8` if you're not using that version.

**Comment by jadhavsuraj73** [comment]
I am using version 2.0.0,
    compile 'com.braintreepayments.api:braintree:2.0.0'
    compile 'com.braintreepayments.api:drop-in:2.0.0'
is this fixed in the newer version?

**Comment by quinnjn** [comment]
It looks like we might have made a fix for this in `2.1.1`. Here is a [related issue in braintree_android](https://github.com/braintree/braintree_android/issues/83).

Let us know if you still have the issue after upgrading to the latest 2.x Drop-in: `2.3.8`.

**Comment by sdcoffey** [comment]
Hey @jadhavsuraj73,

It's been a few days since there's been any movement on this issue, so I'm going to close it for now. Let us know if it pops back up again!
